name: iml.env
channels:
  - defaults
dependencies:
  - nb_conda_kernels
  - pandas
  - scipy
  - plotly
  - psutil
  - nb_conda
  - requests
  - numpy
  - scikit-learn
  - python
  - plotly-orca
  - matplotlib
  - statsmodels
  - pip
  - pip:
    - gif
    - kaleido
    - pillow
